### ISSUE TITLE
Socket Setup

### ISSUE THREAD

**Issue by aaron-zx** [chbsk/ARS430_RDI_Driver#1]
Hi, I would like to request for your help please, I'm trying to connect this radar to ROS Kinetic in Ubuntu 18.04; I'm receiving UDP packages in Wireshark, but not with your driver; as you explained in the Readme I have to change the network addresses, but I do not know exactly which parameters I have to change in the repository, if it is only in the scripts or where and how do I get them from Wireshark.

I have been testing by only changing the next parameters within online_extract_radar.py and online_extract_handshake.py, but I really don't know if that is enough or what other places I have to change and from where I can know these values in Wireshark :

**MCAST_GRP:** I have left the one you wrote, but I have also tested the destination address from the MDNS and UDP package
**MCAST_PORT**: In the UDP package says 31122, but in MDNS says 5353
**socket.inet_aton and host:** I'm putting the same direction in both  spaces, actually the one Wireshark tells me it is receiving ethernet signal from in the start page where it shows small traffic graphs. Also I have put this address as fixed in the Wired Connection from Ubuntu.

Thanks in advance, hope to hear from you soon.

**Comment by chbsk** [comment]
Hey Aaron, I believe online_extract_handshake.py is an artifact of the development process and was merged into online_extract_radar.py

You can check the launch file to traverse other dependencies. I recall the IP and port were the only parameters that needed to be changed. If you are receiving your packets at a different ip and port I suggest you try those in online_radar_extract.py. I believe you should be able to roslaunch the script separately.

**Comment by aaron-zx** [comment]
Thank you for your quick response, however, I am still not able to communicate it; in the host direction I must put the destination address (239.192.22.10) or the source (10.1.1.21) or what address should I put?
Thanks in advance!
